version: '3.7'

services:
    nginx:
        restart: always
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: hazen_nginx
        ports:
          - "8080:8080"
        networks:
          - frontend

    redis:
        image: redis:latest
        container_name: hazen_redis
        hostname: redis
        networks:
            - backend

    hazen_db:
        image: postgres:13.1
        container_name: hazen_db
        restart: always
        expose:
            - "5432"
        networks:
            - backend
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        volumes:
            - $APP_DATA_DIR/db:/var/lib/postgresql/data

    web:
        restart: always
        build:
            context: .
            dockerfile: docker/hazen_app/Dockerfile
        image: hazen_app
        container_name: hazen_web_app
        depends_on:
            - hazen_db
            - redis
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - RUNNING_ON_DOCKER=true
        networks:
            - frontend
            - backend
        volumes:
            - $APP_DATA_DIR/web:/APP/uploads
        ports:
            - "5001:5001"
        command: docker/hazen_app/start_app.sh

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
