version: '3.7'

services:
    nginx:
        container_name: hazen_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        networks:
            - frontend
        ports:
            - "8080:8080"
        restart: always

    redis:
        image: redis:latest
        container_name: hazen_redis
        hostname: redis
        networks:
            - backend

    hazen_db:
        container_name: hazen_db
        image: postgres:13.1
        networks:
            - backend
        expose:
            - "5432"
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        volumes:
            - $APP_DATA_DIR/db:/var/lib/postgresql/data
        restart: always

    web:
        container_name: hazen_web_app
        image: hazen_app
        build:
            context: .
            dockerfile: docker/hazen_app/Dockerfile
        depends_on:
            - hazen_db
            - redis
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - RUNNING_ON_DOCKER=true
        volumes:
            - $APP_DATA_DIR/web:/APP/uploads
        networks:
            - frontend
            - backend
        ports:
            - "5001:5001"
        command: docker/hazen_app/start_app.sh
        restart: always

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
