version: '3.3'

services:
    nginx:
        restart: always
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: hazen_nginx
        ports:
          - "8080:8080"
        networks:
          - frontend

    redis:
        image: redis:latest
        hostname: redis
        networks:
            - backend

    hazen_db:
        image: postgres:13.1
        restart: always
        build:
            context: .
            dockerfile: docker/postgres/Dockerfile
        expose:
            - "5432"
        networks:
            - backend
        environment:
            - POSTGRES_DB=hazen
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=rootpass1
        volumes:
            - type: bind
              source: ~/HAZEN_APP_DATA/db
              target: /var/lib/postgresql/data

    web:
        restart: always
        build:
            context: .
            dockerfile: docker/hazen_app/Dockerfile
        image: hazen_app
        container_name: hazen_web_app
        depends_on:
            - hazen_db
            - redis
        networks:
            - frontend
            - backend
        volumes:
            - type: bind
              source: ~/HAZEN_APP_DATA/web
              target: /APP/uploads
        ports:
            - "5001:5001"
        command: docker/hazen_app/start_app.sh

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
