"""Add docstring column to task table

Revision ID: 0eee51f745b0
Revises: 1544418d922f
Create Date: 2023-04-04 21:57:04.844332

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0eee51f745b0'
down_revision = '1544418d922f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('task', sa.Column('docstring', sa.String(length=6000), nullable=True))

    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_column('task', 'docstring')
    op.add_column('series', sa.Column('pixel', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('fact',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('acquisition_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('process_task', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('process_task_variables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], name='fact_acquisition_id_fkey'),
    sa.ForeignKeyConstraint(['process_task'], ['process_task.id'], name='fact_process_task_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fact_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fact_pkey')
    )
    op.create_table('process_task',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('docstring', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='process_task_pkey')
    )
    op.create_table('acquisition',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('files', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('series_instance_uid', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='acquisition_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='acquisition_pkey')
    )
    # ### end Alembic commands ###
