"""empty message

Revision ID: 1544418d922f
Revises: 84124366c36a
Create Date: 2022-02-22 15:22:35.310323

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1544418d922f'
down_revision = '84124366c36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###



    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact')
    op.drop_table('acquisition')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('process_task')
    # ### end Alembic commands ###
