"""create image study device tables

Revision ID: 5b29621c4aea
Revises: baf5cfd2f6af
Create Date: 2024-03-07 22:56:46.221296

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "5b29621c4aea"
down_revision = "baf5cfd2f6af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("institution", sa.String(length=100), nullable=True),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("device_model", sa.String(length=100), nullable=True),
        sa.Column("station_name", sa.String(length=100), nullable=True),
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "study",
        sa.Column("uid", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("study_date", sa.String(length=64), nullable=True),
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "image",
        sa.Column("uid", sa.String(length=100), nullable=True),
        sa.Column("filename", sa.String(length=200), nullable=True),
        sa.Column("accession_number", sa.String(length=100), nullable=True),
        sa.Column("series_id", postgresql.UUID(), nullable=True),
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image")
    op.drop_table("study")
    op.drop_table("device")
    # ### end Alembic commands ###
