"""create report table

Revision ID: baf5cfd2f6af
Revises: f67e738bcb3c
Create Date: 2024-03-07 22:53:06.345059

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "baf5cfd2f6af"
down_revision = "f67e738bcb3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column("hazen_version", sa.String(length=10), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("series_id", postgresql.UUID(), nullable=True),
        sa.Column("task_name", sa.String(length=100), nullable=True),
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_name"],
            ["task.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report")
    # ### end Alembic commands ###
