"""empty message

Revision ID: cb1c369dca73
Revises: 5b01b2c8311b
Create Date: 2019-01-02 10:32:30.073713

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app import db


# revision identifiers, used by Alembic.
revision = 'cb1c369dca73'
down_revision = '5b01b2c8311b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
