"""create series table

Revision ID: f67e738bcb3c
Revises: 85a111fab851
Create Date: 2024-03-07 22:51:56.567672

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "f67e738bcb3c"
down_revision = "85a111fab851"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column("uid", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("series_datetime", sa.DateTime(), nullable=True),
        sa.Column("has_report", sa.Boolean(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("series")
    # ### end Alembic commands ###
